### ISSUE TITLE
"Cannot find the path" on Windows

### ISSUE THREAD

**Issue by simevidas** [edenspiekermann/sprite.sh#3]
I assume Windows is not supported due to Shell? I’m using Cmder, which I think, provides Unix commands but I don't know if that's relevant in this case.

![capture](https://cloud.githubusercontent.com/assets/716405/12968209/0dfeadc4-d06f-11e5-8687-26d88cb4923c.PNG)

**Comment by KittyGiraudel** [comment]
Oh. We are using Mac OS X only here so to be entirely honest I could not try it on Windows. Maybe @valeriangalliat can give us a hand here?

**Comment by KittyGiraudel** [comment]
I have been investigating a bit and apparently I am using some commands that are not supported on Windows environments, such as `cat` or `rm -rf`.

A solution would be to port this script over to Node.js to ensure compatibility, but this is not something I am willing to do myself given I mostly wrote it for Edenspiekermann where we only deal with Mac OS X (and more broadly speaking Unix).

I’d still like Valérian’s opinion. We never know. Maybe he can do magic. :)

**Comment by valeriangalliat** [comment]
Only Unix systems for me too, don't have a Windows at hand.
But if Cmder provide Unix commands, I bet it contains `cat` and `rm`.

The problem here is that the script is not actually running. The error you see every time is either your shell not finding the `spritesh` command in your `PATH`, or not finding `/bin/bash` (from the shebang).

I don't know Cmder at all but I would investigate on these options. If `which spritesh` or `command -v spritesh` does not error and shows the right path to `spritesh`, then it's a problem with the shebang. Do you know if Cmder interprets shebangs, and if you have a Bash implementation at hand? Or at least a `sh` implementation (at first sight `spritesh` can run on bare `sh`).

**Comment by TxHawks** [comment]
You need a proper terminal.
[Cygwin](https://www.cygwin.com/) and [git-bash](https://git-for-windows.github.io/) would do the trick in windows.

Just run the script from inside one of them.

**Comment by simevidas** [comment]
@TxHawks I can confirm that it works in Git Bash. I doubt that there are many developers on Windows that have Node installed but not Git, so this is a solid workaround.

**Comment by KittyGiraudel** [comment]
Very good. :)
